on:
  push:
  workflow_dispatch:

jobs:
  foo1:
    runs-on: ubuntu-latest
    steps:
      - name: generate output
        id: generate-output
        run: echo "::set-output name=bar-output::$(echo 0)"
    outputs:
      foo1-output: ${{ steps.generate-output.outputs.bar-output }}
  foo2:
    needs: foo1
    runs-on: ubuntu-latest
    # if: ${{ needs.generate-output.outputs.foo1-output != 0 }}
    steps:
      - name: print foo1 output
        env:
          foo1_OUTPUT: ${{ needs.foo1.outputs.bar-output }}
        run: echo "$foo1_OUTPUT"
