on: push

jobs:
  one:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Write variables
        run: |
          FOO=$(echo "this is FOO")
          echo $FOO
          echo "BAR='this is BAR'" >> $GITHUB_ENV
          echo $BAR
