on: push

env:
  FOO: job-${{ github.job }}-${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  one:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Write variables
        env:
          FOO: "bar"
        run: |
          env
          echo "'VARIABLE=${{ env.FOO }}'"
          echo "home: $HOME"
