on: push

jobs:
  one:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Write $HOME and env.HOME to stdout
        run: |
          env
          echo "home: ${{ env.HOME }}"
          echo "home: $HOME"
