on:
  push:
  workflow_dispatch:

jobs:
  foo1:
    runs-on: ubuntu-latest
    steps:
      - name: generate output
        id: generate-output
        run: echo "::set-output name=foo1-output::$(echo 1)"
    outputs:
      foo1-output: ${{ steps.generate-output.outputs.foo1-output }}
  foo2:
    needs: foo1
    runs-on: ubuntu-latest
    if: ${{ needs.generate-output.outputs.foo1-output != 0 }}
    steps:
      - name: print success
        run: echo "success"
