on:
  push:

jobs:
  foo1:
    runs-on: ${{ matrix.os[0] }}
    strategy:
      matrix:
        os: [[ubuntu-20.04, 3.8], [ubuntu-18.04, 3.7]]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.os[1] }}
      - name: Print Python Version
        run: python --version
      - run: pwd
