on:
  push:
  workflow_dispatch:

jobs:
  make_artifact:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          # - 'windows-latest'
          # - 'macos-latest'
    steps:
      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}
      - name: Install latest version of Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          pip install poetry
      # - name: Add Poetry to PATH
      #   run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Check poetry version
        run: poetry --version
