on: push, workflow_dispatch

jobs:
  make_artifact:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          # - 'windows-latest'
          # - 'macos-latest'
    steps:
      - name: write to env var
        run: echo 'bar="foo"' >> "$GITHUB_ENV"

      - name: echo env var
        run: echo "$bar"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Get runner OS
        env:
          RUNNER_OS: ${{ runner.os }}
        run: echo "$RUNNER_OS"
      - name: Create file with runner OS in name
        env:
          OS_FILENAME: 'spam-${{ runner.os }}.zip'
        run: touch "./$OS_FILENAME"
      - name: List created file
        run: ls -l "./$OS_FILENAME"
      - name: Create artifact
        run: touch "./$ARTIFACT_NAME"
      - name: List artifact
        run: ls -l "./$ARTIFACT_NAME"
